server:
  port: 8081
  servlet:
    context-path: /user-service

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/subproject_nhom03_kttkpm14
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  # cloud config
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      name: eureka-config
      uri:
      - http://localhost:8888





